repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [-c, .markdownlint.yaml]

  - repo: local
    hooks:
      - id: exiftool
        name: remove exif
        language: system
        entry: exiftool -all= -overwrite_original
        types: ["image"]
